AWSTemplateFormatVersion: 2010-09-09
Description: SageMaker Model template

Parameters:
  Service:
    Description: service name
    Type: String
    Default: sbs
    AllowedValues:
      - sbs
  AccountType:
    Description: Account Type
    Type: String
    Default: dva
    AllowedValues:
      - dva
  ModelName:
    Description: Model Name
    Type: String
  ModelPath:
    Description: Model Input Bucket Path
    Type: String
  ECRImageUri:
    Description: ECR Image ARN
    Type: String

Mappings:
    RegionMap:
      ap-northeast-1:
        "Abbreviation": an1
      ap-southeast-2:
        "Abbreviation": as2
      eu-west-1:
        "Abbreviation": ew1
      eu-central-1:
        "Abbreviation": ec1
      us-west-2:
        "Abbreviation": uw2
      us-east-1:
        "Abbreviation": ue1

Resources:
  SageMakerModel:
    Type: AWS::SageMaker::Model
    Properties:
      ModelName: !Ref ModelName
      ExecutionRoleArn: !Sub
        - arn:aws:iam::${AWS::AccountId}:role/${Service}-${RegionShort}-sagemaker-role
        - RegionShort:
            !FindInMap [RegionMap, !Ref AWS::Region, "Abbreviation"]
      PrimaryContainer:
        ModelDataUrl: !Ref ModelPath
        Image: !Ref ECRImageUri
      Tags:
        - Key: Owner
          Value: !Ref Service