AWSTemplateFormatVersion: 2010-09-09
Description: sbs SageMaker role

Parameters:
  ServiceId:
    Description: Service ID
    Type: String
    Default: sbs
    AllowedValues:
      - sbs
  
Mappings:
  RegionMap:
    ap-northeast-1:
      "Abbreviation": an1
    ap-southeast-2:
      "Abbreviation": as2
    eu-west-1:
      "Abbreviation": ew1
    eu-central-1:
      "Abbreviation": ec1
    us-west-2:
      "Abbreviation": uw2
    us-east-1:
      "Abbreviation": ue1

Resources:
  SageMakerRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action:
              - sts:AssumeRole
            Principal:
              Service: sagemaker.amazonaws.com
        Version: 2012-10-17
      RoleName: !Sub
        - ${ServiceId}/${ServiceId}-${RegionShort}-sagemaker-role
        - RegionShort:
            !FindInMap [RegionMap, !Ref AWS::Region, "Abbreviation"]
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
          